### ISSUE TITLE
Disabled Menu Item is NOT having item separator

### ISSUE THREAD

**Issue by RahulSDeshpande** [mikepenz/HoloKitKatDrawer#2]
Hi @mikepenz..

As enabled menu item has item separator, disabled menu item is not having any seperator..

It looks just as naked as a simple menu item..

Please help me on this @mikepenz..

:D

**Comment by mikepenz** [comment]
@RahulSDeshpande there's now a new project for creating an easy and simple and awesome MaterialDrawer :D ->  https://github.com/mikepenz/MaterialDrawer

**Comment by RahulSDeshpande** [comment]
Hi @mikepenz..

Yes.. I have referred that.. and I am using it in my projects :cake:
And it is HELL EASY & AMAZING bro..!!

Thanks a lot..!!
